//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomDatabaseConnectorDll.CustomDatabase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomDatabaseConnectorDll.CustomDatabase.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET-class doesn&apos;t contain a CustomDatabaseClassAnnotation. Please add annotation.
        /// </summary>
        internal static string ANN_CLASS_NO_ANNOTATION {
            get {
                return ResourceManager.GetString("ANN_CLASS_NO_ANNOTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET-class doesn&apos;t contain properties with a CustomDatabaseColumnAnnotation. Make sure you have at least one property.
        /// </summary>
        internal static string ANN_CLASS_NO_COLUMNS {
            get {
                return ResourceManager.GetString("ANN_CLASS_NO_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET-column doesn&apos;t contain a CustomDatabaseColumnAnnotation. Please add annotation.
        /// </summary>
        internal static string ANN_COLUMN_NO_ANNOTATION {
            get {
                return ResourceManager.GetString("ANN_COLUMN_NO_ANNOTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableName property is empty. Please set this property.
        /// </summary>
        internal static string ANN_NO_CLASSNAME_INSERTED {
            get {
                return ResourceManager.GetString("ANN_NO_CLASSNAME_INSERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columnname is empty. Please set columnname.
        /// </summary>
        internal static string ANN_NO_COLUMNNAME_INSERTED {
            get {
                return ResourceManager.GetString("ANN_NO_COLUMNNAME_INSERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No primary key annotations found. Please define at least one primary key column.
        /// </summary>
        internal static string ANN_NO_PRIMARY_KEY {
            get {
                return ResourceManager.GetString("ANN_NO_PRIMARY_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datatype hasn&apos;t been defined in code. Please contact owner of this DLL.
        /// </summary>
        internal static string DATATYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("DATATYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string for DB is empty.
        /// </summary>
        internal static string DB_EMPTY_CONNECTIONSTRING {
            get {
                return ResourceManager.GetString("DB_EMPTY_CONNECTIONSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database hasn&apos;t been initialized.
        /// </summary>
        internal static string DB_NOT_INITIALIZED {
            get {
                return ResourceManager.GetString("DB_NOT_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch between number of columns &amp; generated columns.
        /// </summary>
        internal static string MISMATCH {
            get {
                return ResourceManager.GetString("MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .NET-property is passed to method.
        /// </summary>
        internal static string NO_DOTNET_PROPERTY_PASSED {
            get {
                return ResourceManager.GetString("NO_DOTNET_PROPERTY_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No object is passed to method.
        /// </summary>
        internal static string NO_OBJECT_PASSED {
            get {
                return ResourceManager.GetString("NO_OBJECT_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No objecttype is passed to method.
        /// </summary>
        internal static string NO_OBJECTTYPE_PASSED {
            get {
                return ResourceManager.GetString("NO_OBJECTTYPE_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key is empty.
        /// </summary>
        internal static string SQL_EMPTY_PKEY {
            get {
                return ResourceManager.GetString("SQL_EMPTY_PKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL-Statement is empty..
        /// </summary>
        internal static string SQL_EMPTY_STATEMENT {
            get {
                return ResourceManager.GetString("SQL_EMPTY_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key exists of multiple columns. Change referred table {0} to just one primary key.
        /// </summary>
        internal static string SQL_FKEY_MULTIPLE_COLUMNS {
            get {
                return ResourceManager.GetString("SQL_FKEY_MULTIPLE_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No foreign key found for table {0}.
        /// </summary>
        internal static string SQL_NO_FKEY_FOUND {
            get {
                return ResourceManager.GetString("SQL_NO_FKEY_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No where-clause..
        /// </summary>
        internal static string SQL_NO_WHERE_CLAUSE {
            get {
                return ResourceManager.GetString("SQL_NO_WHERE_CLAUSE", resourceCulture);
            }
        }
    }
}
